version: 2.1
orbs:
  soda-lint: checkmoney/soda-lint@1.0.2
  jest: checkmoney/jest@1.0.0
  npm: checkmoney/npm@1.0.0
workflows:
  version: 2
  build:
    jobs:
      - soda-lint/invoke:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - jest/test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - npm/publish:
          npm_token: NPM_TOKEN
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - soda-lint/invoke
            - jest/test
